swagger: "2.0"
info:
  description: "Possible API endpoints for phase two of Argent Bank project."
  version: "1.0.0"
  title: "Argent Bank API Documentation"
  termsOfService: "http://swagger.io/terms/"

host: "localhost:3001"
basePath: "/api/v2"
tags:
- name: "User Account"
  description: "Endpoints for user's account data"
- name: "User Transactions"
  description: "Endpoints for user's transactions data"
schemes:
- "https"
- "http"
paths:
  /user/account:
    get:
      tags:
      - "User Account"
      summary: "Summary of user's account"
      description: "API to fetch user's account summary"
      operationId: "userAccount"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "header"
        name: "Authorization"
        type: "string"
        description: "Attach Bearer JWT Token"
        required: true
      responses:
        "200":
          description: "User account details retrieved succesfully"
          schema:
            items:
              $ref: "#/definitions/AccountsSummary"
        "400":
          description: "Invalid token"
        "500":
          description: "Internal server error"
          
  /user/account/${accountID}/transaction:
    get:
      tags:
      - "User Transactions"
      summary: "Transactions for the selected type of account"
      description: "API to fetch user's transactions in one type of account"
      operationId: "userTransaction"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "header"
        name: "Authorization"
        type: "string"
        description: "Attach Bearer JWT Token"
        required: true
      - in: path
        name: accountID
        type: integer
        required: true
        description: "Numeric ID of the account to get"
      responses:
        "200":
          description: "User transactions retrieved succesfully"
          schema:
            items:
              $ref: "#/definitions/AccountTransactions"
        "400":
          description: "Invalid token"
        "500":
          description: "Internal server error"

  /user/account/${accountID}/transaction/${transactionID}:
    get:
      tags:
      - "User Transactions"
      summary: "Transaction details for the selected transaction ID"
      description: "API to fetch user's transaction details"
      operationId: "userTransactionDetail"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "header"
        name: "Authorization"
        type: "string"
        description: "Attach Bearer JWT Token"
        required: true
      - in: path
        name: accountID
        type: integer
        required: true
        description: "Numeric ID of the account to get"
      - in: path
        name: transactionID
        type: integer
        required: true
        description: "Numeric ID of the transaction to get"
      responses:
        "200":
          description: "User transaction details retrieved succesfully"
          schema:
            items:
              $ref: "#/definitions/TransactionDetails"
        "400":
          description: "Invalid token"
        "500":
          description: "Internal server error"
    put:
      tags:
      - "User Transactions"
      summary: "Update transaction details"
      description: ""
      operationId: "updateSavings"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "header"
        name: "Authorization"
        type: "string"
        description: "Attach Bearer JWT Token"
        required: true
      - in: "body"
        name: "body"
        description: "Details that need to be updated"
        required: true
        schema:
          $ref: "#/definitions/UpdateTransactionDetails"
      - in: path
        name: accountID
        type: integer
        required: true
        description: "Numeric ID of the account to get"
      - in: path
        name: transactionID
        type: integer
        required: true
        description: "Numeric ID of the transaction to get"
      responses:
        "200":
          description: Transaction details updated succesfully"
          schema:
            items:
              $ref: "#/definitions/APIResponse"
        "400":
          description: "Invalid fields"
        "500":
          description: "Internal server error"
          
definitions:
  AccountsSummary:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
      body:
        type: "object"
        properties:
          balance: 
            type: "integer"
          type: 
            type: "string"
            
  AccountTransactions:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
      transaction:
        type: "object"
        properties:
          date:
            type: "string"
          description:
            type: "string"
          amount:
            type: "integer"
              
  TransactionDetails:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
      details:
        type: "object"
        properties:
          type:
            type: "string"
          category:
            type: "string"
          notes:
            type: "integer"
              
  UpdateTransactionDetails:
    type: "object"
    properties:
      category:
        type: "string"
      notes:
        type: "string"
        
  APIResponse:
    type: "object"
    properties:
      status:
        type: "integer"
        format: "int32"
      message:
        type: "string"
      body:
        type: "object"
        properties:
          category:
            type: "string"
          notes:
            type: "string"
